image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  AWS_EC2_IP: ${AWS_EC2_IP}
  AWS_SSH_KEY: ${AWS_SSH_KEY}
  AWS_USER: ${AWS_USER}
  DOCKER_REGISTRY: ${CI_REGISTRY}
  DOCKER_IMAGE: ${CI_REGISTRY}/aradhya24/cold-email-generator:${CI_COMMIT_SHA}

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - .cache/pip
    - venv/

test:
  image: python:3.9-slim
  stage: test
  before_script:
    - apt-get update && apt-get install -y python3-pip python3-venv
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt || pip install --no-deps --use-pep517 -r requirements.txt
    - pip install pytest pytest-cov flake8
    - mkdir -p tests && touch tests/__init__.py
  script:
    - flake8 app/ --config=setup.cfg
    - pytest --cov=app --cov-report=xml --cov-report=term-missing tests/
    - if [ ! -f coverage.xml ]; then echo '<?xml version="1.0" ?><coverage></coverage>' > coverage.xml; fi
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml

build:
  stage: build
  script: docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY && docker build --pull -t $DOCKER_IMAGE . && docker tag $DOCKER_IMAGE $CI_REGISTRY/aradhya24/cold-email-generator:latest && docker push $DOCKER_IMAGE && docker push $CI_REGISTRY/aradhya24/cold-email-generator:latest
  only:
    - main

deploy:
  stage: deploy
  image: python:3.9-slim
  only:
    - main
  script:
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$AWS_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh ${AWS_USER}@${AWS_EC2_IP} "mkdir -p ~/app/vectorstore ~/app/app/resource ~/app/.streamlit"
    - echo "GROQ_API_KEY = \"${GROQ_API_KEY}\"" > secrets.toml
    - echo "CI_REGISTRY=${CI_REGISTRY}" > .env.deploy
    - echo "CI_COMMIT_SHA=${CI_COMMIT_SHA}" >> .env.deploy
    - echo "GROQ_API_KEY=${GROQ_API_KEY}" >> .env.deploy
    - scp docker-compose.yml ${AWS_USER}@${AWS_EC2_IP}:~/app/
    - scp secrets.toml ${AWS_USER}@${AWS_EC2_IP}:~/app/.streamlit/
    - scp .env.deploy ${AWS_USER}@${AWS_EC2_IP}:~/app/.env
    - scp -r app/resource/* ${AWS_USER}@${AWS_EC2_IP}:~/app/app/resource/ || true
    - ssh ${AWS_USER}@${AWS_EC2_IP} "sudo apt-get update && sudo apt-get install -y docker.io docker-compose curl || true"
    - ssh ${AWS_USER}@${AWS_EC2_IP} "sudo usermod -aG docker $USER || true"
    - ssh ${AWS_USER}@${AWS_EC2_IP} "sudo systemctl start docker || true"
    - ssh ${AWS_USER}@${AWS_EC2_IP} "sudo chown -R $USER:$USER ~/app"
    - ssh ${AWS_USER}@${AWS_EC2_IP} "cd ~/app && docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY && docker-compose down && docker system prune -f || true"
    - ssh ${AWS_USER}@${AWS_EC2_IP} "cd ~/app && docker-compose pull && docker-compose up -d"
