version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - USER_AGENT=${USER_AGENT}
    volumes:
      - ./app:/app/app
      - ./vectorstore:/app/vectorstore
    restart: unless-stopped 