name: Deploy Cold Email Generator

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      setup_infrastructure:
        description: 'Set up AWS infrastructure'
        required: false
        default: true
        type: boolean

env:
  APP_NAME: cold-email
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Run infrastructure script
        run: |
          echo "Setting up infrastructure..."
          chmod +x deploy/aws-k8s/aws-infrastructure.sh
          cd deploy/aws-k8s
          ./aws-infrastructure.sh
          cd ../..
          echo "Infrastructure setup completed." 