name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_USER: ubuntu

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Validate Python imports
        run: python -c "import app.main" || echo "Validation failed but continuing"

  build:
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}
            ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    env:
      LB_DNS: ''
    outputs:
      public_ip: ${{ env.PUBLIC_IP }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Set up SSH
        id: ssh_key
        run: |
          mkdir -p ~/.ssh ssh_keys
          chmod 700 ~/.ssh
          echo "Generating new SSH key..."
          ssh-keygen -t rsa -b 2048 -f ~/.ssh/ec2_key -N ""
          chmod 600 ~/.ssh/ec2_key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/ec2_key
          
          # Save SSH keys for monitor stage
          cp ~/.ssh/ec2_key ssh_keys/
          cp ~/.ssh/ec2_key.pub ssh_keys/
          
          # Create SSH config
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
      - name: Upload SSH keys
        uses: actions/upload-artifact@v4
        with:
          name: ssh-keys
          path: ssh_keys/
          retention-days: 1
          
      - name: Launch EC2 Instance
        run: |
          # Check required variables
          if [ -z "${{ secrets.EC2_SECURITY_GROUP }}" ]; then
            echo "ERROR: EC2_SECURITY_GROUP is not set"
            exit 1
          fi
          
          if [ -z "${{ secrets.EC2_SUBNET_ID }}" ]; then
            echo "ERROR: EC2_SUBNET_ID is not set"
            exit 1
          fi
          
          # Store SSH public key in a variable
          SSH_PUBLIC_KEY=$(cat ~/.ssh/ec2_key.pub)
          
          # Create user data script with proper debugging
          cat > userdata.sh << EOF
          #!/bin/bash
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          echo "Starting user data script execution..."
          
          # Create ubuntu user SSH directory with proper permissions
          echo "Setting up SSH directory..."
          mkdir -p /home/ubuntu/.ssh
          chmod 700 /home/ubuntu/.ssh
          
          # Add SSH key to authorized_keys
          echo "Adding SSH key to authorized_keys..."
          echo "${SSH_PUBLIC_KEY}" > /home/ubuntu/.ssh/authorized_keys
          
          # Set proper permissions
          echo "Setting proper permissions..."
          chmod 600 /home/ubuntu/.ssh/authorized_keys
          chown -R ubuntu:ubuntu /home/ubuntu/.ssh
          
          # Update package lists
          echo "Updating package lists..."
          apt-get update
          
          # Install required packages
          echo "Installing required packages..."
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            python3-pip \
            docker.io \
            curl \
            apt-transport-https \
            ca-certificates \
            software-properties-common
          
          # Start and enable Docker
          echo "Starting Docker service..."
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ubuntu
          
          # Verify Docker installation
          echo "Verifying Docker installation..."
          docker --version
          systemctl status docker --no-pager
          
          echo "User data script completed successfully."
          EOF
          
          chmod +x userdata.sh
          
          echo "Launching EC2 instance..."
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0c7217cdde317cfec \
            --instance-type t2.micro \
            --security-group-ids ${{ secrets.EC2_SECURITY_GROUP }} \
            --subnet-id ${{ secrets.EC2_SUBNET_ID }} \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=cold-email-instance}]" \
            --user-data file://userdata.sh \
            --associate-public-ip-address \
            --query 'Instances[0].InstanceId' \
            --output text)
            
          if [ -z "$INSTANCE_ID" ]; then
            echo "Failed to launch EC2 instance"
            exit 1
          fi
          
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          
          echo "Waiting for instance to be running..."
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
          
          echo "Waiting additional time for instance setup..."
          sleep 90  # Increased wait time to ensure user data script completes
          
          # Get public IP with retries
          MAX_RETRIES=5
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i to get public IP..."
            PUBLIC_IP=$(aws ec2 describe-instances \
              --instance-ids $INSTANCE_ID \
              --query 'Reservations[0].Instances[0].PublicIpAddress' \
              --output text)
              
            if [ ! -z "$PUBLIC_IP" ] && [ "$PUBLIC_IP" != "None" ] && [ "$PUBLIC_IP" != "null" ]; then
              echo "Found public IP: $PUBLIC_IP"
              echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
              echo "LB_DNS=$PUBLIC_IP" >> $GITHUB_ENV
              break
            fi
            
            if [ $i -eq $MAX_RETRIES ]; then
              echo "Failed to get public IP after $MAX_RETRIES attempts"
              aws ec2 terminate-instances --instance-ids $INSTANCE_ID
              exit 1
            fi
            
            echo "Waiting 20 seconds before retry..."
            sleep 20
          done
          
          # Test SSH connection with improved debugging
          echo "Testing SSH connection..."
          for i in {1..6}; do
            echo "SSH attempt $i: Trying to connect to ubuntu@$PUBLIC_IP..."
            if ssh -v -i ~/.ssh/ec2_key -o ConnectTimeout=10 -o BatchMode=yes ubuntu@$PUBLIC_IP "echo 'SSH connection successful'"; then
              echo "SSH connection established successfully"
              break
            fi
            echo "Attempt $i failed. Checking instance status..."
            aws ec2 describe-instance-status --instance-ids $INSTANCE_ID
            
            if [ $i -eq 6 ]; then
              echo "Failed to establish SSH connection after all attempts"
              echo "Fetching instance console output for debugging..."
              aws ec2 get-console-output --instance-id $INSTANCE_ID
              aws ec2 terminate-instances --instance-ids $INSTANCE_ID
              exit 1
            fi
            
            echo "Waiting 20 seconds before next attempt..."
            sleep 20
          done
          
      - name: Wait for SSH and Deploy
        run: |
          # Setup directories
          ssh -i ~/.ssh/ec2_key ubuntu@${{ env.PUBLIC_IP }} "sudo mkdir -p /opt/cold-email/{app,scripts,k8s} && sudo chown -R ubuntu:ubuntu /opt/cold-email"
          
          # Copy files
          scp -i ~/.ssh/ec2_key -r app scripts k8s ubuntu@${{ env.PUBLIC_IP }}:/opt/cold-email/
          
          # Setup environment
          ssh -i ~/.ssh/ec2_key ubuntu@${{ env.PUBLIC_IP }} "echo 'GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}' | sudo tee /opt/cold-email/app/.env"
          ssh -i ~/.ssh/ec2_key ubuntu@${{ env.PUBLIC_IP }} "chmod +x /opt/cold-email/scripts/*.sh"
          
          # Run setup and deployment
          ssh -i ~/.ssh/ec2_key ubuntu@${{ env.PUBLIC_IP }} "cd /opt/cold-email && sudo ./scripts/setup-k8s.sh"
          ssh -i ~/.ssh/ec2_key ubuntu@${{ env.PUBLIC_IP }} "cd /opt/cold-email && sudo ./scripts/deploy-k8s.sh"

  monitor:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Download SSH keys
        uses: actions/download-artifact@v4
        with:
          name: ssh-keys
          path: ssh_keys
          
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          cp ssh_keys/ec2_key ~/.ssh/
          cp ssh_keys/ec2_key.pub ~/.ssh/
          chmod 600 ~/.ssh/ec2_key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/ec2_key
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > ~/.ssh/config
          
      - name: Monitor Deployment
        run: |
          # Get instance IP with improved error handling
          MAX_RETRIES=5
          RETRY_DELAY=10
          
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i to get EC2 instance info..."
            
            INSTANCE_INFO=$(aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=cold-email-instance" "Name=instance-state-name,Values=running" \
              --query "Reservations[*].Instances[*].[InstanceId,PublicIpAddress]" \
              --output text)
              
            EC2_IP=$(echo "$INSTANCE_INFO" | awk '{print $2}')
            
            if [ ! -z "$EC2_IP" ] && [ "$EC2_IP" != "None" ] && [ "$EC2_IP" != "null" ]; then
              echo "Found EC2 instance with IP: $EC2_IP"
              break
            fi
            
            if [ $i -eq $MAX_RETRIES ]; then
              echo "Failed to get EC2 instance IP after $MAX_RETRIES attempts"
              exit 1
            fi
            
            echo "No valid IP found, waiting $RETRY_DELAY seconds before retry..."
            sleep $RETRY_DELAY
          done
          
          # Test SSH connection with retries
          echo "Testing SSH connection to $EC2_IP..."
          for i in $(seq 1 3); do
            if ssh -i ~/.ssh/ec2_key -o ConnectTimeout=10 -o BatchMode=yes ubuntu@$EC2_IP "echo 'SSH connection successful'"; then
              echo "SSH connection established on attempt $i"
              break
            fi
            if [ $i -eq 3 ]; then
              echo "Failed to establish SSH connection after 3 attempts"
              exit 1
            fi
            echo "SSH connection failed, waiting 10 seconds before retry..."
            sleep 10
          done
          
          # Check Kubernetes status with improved error handling
          echo "Checking Kubernetes cluster status..."
          for cmd in \
            "sudo kubectl get nodes" \
            "sudo kubectl get pods --all-namespaces" \
            "sudo kubectl get pods -n default -l app=cold-email-generator" \
            "sudo kubectl get svc -n default"; do
            echo "Running: $cmd"
            if ! ssh -i ~/.ssh/ec2_key ubuntu@$EC2_IP "$cmd"; then
              echo "Failed to execute: $cmd"
              exit 1
            fi
          done 